image:
  repository: ghcr.io/originalgonzo/wiz-exercise-app
  tag: latest
  pullPolicy: Always

replicaCount: 2

service:
  type: LoadBalancer
  port: 80

db:
  uri: ""

backup:
  enabled: true
  bucket: ""
  awsRegion: "us-east-1"
  schedule: "0 * * * *"
  irsaRoleArn: ""