apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wizapp.fullname" . }}-mongodb-backup
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "wizapp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.backup.irsaRoleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ . }}
  {{- end }}