apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wizapp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "wizapp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  app.conf: |
    port: 3000