apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wizapp.fullname" . }}-db
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "wizapp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  uri: {{ .Values.db.uri }}