apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wizapp.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "wizapp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
imagePullSecrets:
  - name: ghcr-secret